
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/project9
#    password: 6574
    username: postgres
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:19132/railway
    password: *F51e54532-dEgcC*d4c-bc4cBCBAD3a


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false


jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 86400000 #1 day
  expiration-refresh: 604800000 #7 days

cloudinary:
  cloud_name: drfnzmkqf
  api_key: 348329312131219
  api_secret: RyMSRpJCI1vliEo5dfVICndpc6Y

confirm_url: https://troubled-eyes-project9.up.railway.app/api/v1/auth/email-confirm/