
spring:
  datasource:
    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:52291/railway
    password: LYqvJXrSsLUVTrmLMDSlgOxMsQCoRxDA
    username: postgres
#    url: jdbc:postgresql://localhost:5432/project9
#    password: 6574



  jpa:
    hibernate:
      ddl-auto: update


jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 86400000 #1 day
  expiration-refresh: 604800000 #7 days

cloudinary:
  cloud_name: drfnzmkqf
  api_key: 348329312131219
  api_secret: RyMSRpJCI1vliEo5dfVICndpc6Y

pagesize: 5

confirm_url: https://futuristic-apparel-production.up.railway.app/api/v1/auth/email-confirm/
#confirm_url: localhost:8080/api/v1/auth/email-confirm/