
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:29568/railway
    password: gINrGDzxHMatujjSRgFUIAhVyxRLcoum
    username: postgres

#    url: jdbc:postgresql://localhost:5432/project9
#    password: 6574



  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 86400000 #1 day
  expiration-refresh: 604800000 #7 days

cloudinary:
  cloud_name: drfnzmkqf
  api_key: 348329312131219
  api_secret: RyMSRpJCI1vliEo5dfVICndpc6Y

confirm_url: https://troubled-eyes-project9.up.railway.app/api/v1/auth/email-confirm/
#confirm_url: localhost:8080/api/v1/auth/email-confirm/